addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin"   % "1.0.0")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"           % "1.5.6")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.3.0")
addSbtPlugin("com.typesafe"       % "sbt-mima-plugin"          % "0.8.0")
